// import React from 'react'

const Loader = () => {

  const icon = () =>{
    return (
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="200" height="200" style={{shapeRendering: "auto", display: "block", background: "transparent"}} xmlnsXlink="http://www.w3.org/1999/xlink"><g><g transform="rotate(0 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="-1.7295597484276728s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g transform="rotate(30 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="-1.572327044025157s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g transform="rotate(60 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="-1.4150943396226414s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g transform="rotate(90 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="-1.2578616352201257s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g transform="rotate(120 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="-1.10062893081761s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g transform="rotate(150 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="-0.9433962264150942s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g transform="rotate(180 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="-0.7861635220125786s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g transform="rotate(210 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="-0.6289308176100629s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g transform="rotate(240 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="-0.4716981132075471s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g transform="rotate(270 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="-0.31446540880503143s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g transform="rotate(300 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="-0.15723270440251572s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g transform="rotate(330 50 50)">
  <rect className="fill-primary" height="12" width="6" ry="6" rx="3" y="24" x="47">
    <animate repeatCount="indefinite" begin="0s" dur="1.8867924528301885s" keyTimes="0;1" values="1;0" attributeName="opacity"></animate>
  </rect>
</g><g></g></g>
{/* <!-- [ldio] generated by https://loading.io --> */}
</svg>
    )
  }


  return (
    // <div className="absolute top-0 bottom-0 left-0 right-0 flex flex-wrap justify-center items-center">
    <div className=" absolute top-0, bottom-0 right-0 left-0 h-[100vh] w-[100vw] flex justify-center items-center text-center backdrop-blur-[2px] bg-[#72727233] z-50">
          <button type="button" className="h-[100vh] w-full flex flex-col justify-center items-center text-center" disabled>
            {/* <svg className="mr-3 size-5 animate-spin ..." viewBox="0 0 24 24"> */}
            {icon()}
          </button>
        </div>
        // </div>
  )
}

export default Loader